apiVersion: apps/v1
kind: Deployment
metadata:
  name: cluster-auth-agent
  namespace: cluster-auth
spec:
  replicas: 1
  selector:
    matchLabels:
      addon-agent: cluster-auth
  template:
    metadata:
      labels:
        addon-agent: cluster-auth
    spec:
      serviceAccountName: cluster-auth
      containers:
        - name: addon-agent
          image: docker.io/rokibulhasan114/cluster-auth:latest
          imagePullPolicy: Always
          command:
            - /agent
          args:
            - --leader-elect=false
            - --cluster-name={{ .ClusterName }}
            - --kubeconfig=/etc/hub/kubeconfig
          volumeMounts:
            - name: hub-kubeconfig
              mountPath: /etc/hub/
              readOnly: true
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8081
            initialDelaySeconds: 2
            periodSeconds: 10
      volumes:
        - name: hub-kubeconfig
          secret:
            secretName: cluster-auth-hub-kubeconfig
