apiVersion: v1
description: Cluster Auth Agent
name: cluster-auth-agent
version: v2024.8.9
appVersion: v0.0.3
home: https://github.com/kluster-manager/cluster-auth
icon: https://cdn.appscode.com/images/products/searchlight/icons/android-icon-192x192.png
sources:
- https://github.com/kluster-manager/cluster-auth
maintainers:
- name: appscode
  email: support@appscode.com
