# Image of the managed service-account instances
image: docker.io/rokibulhasan114/cluster-auth
tag:
agentInstallAll: true

# Number of replicas
replicas: 1

enableAddOnDeploymentConfig: false

featureGates:
  ephemeralIdentity: false

agentImagePullSecret: ""

# Hub deploy mode: AddOnTemplate or Deployment
hubDeployMode: Deployment

# Name of the managed service-account addon template, only used when hubDeployMode is AddOnTemplate
# addOnTemplateName: managed-serviceaccount
