apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "cluster-auth.fullname" . }}
  labels:
    {{- include "cluster-auth.labels" . | nindent 4 }}
rules:
# Get cluster id
- apiGroups:
  - ""
  resources:
  - namespaces
  verbs: ["get"]
# create/update rbac objects
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - clusterroles
  - clusterrolebindings
  - roles
  - rolebindings
  verbs: ["*"]
# ocm cluster name detection
- apiGroups:
  - operator.open-cluster-management.io
  resources:
  - klusterlets
  verbs: ["get"]
