kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: cluster-gateway-permission
rules:
- apiGroups:
  - cluster.core.oam.dev
  resources:
  - clustergateways/health
  - clustergateways/proxy
  verbs:
  - "*"
